repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 'master'
    hooks:
    -   id: flake8
        exclude: .git,__pycache__,build,dist
        args: [--max-complexity=10, --max-line-length=120, --ignore=W503]
        types: [python]
        stages: [commit, push]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest tests/
        language: system
        pass_filenames: false
        types: [python]
        stages: [commit, push]
